language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

addons:
  apt:
    packages:
      - graphviz

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -r doc_requirements.txt
  - pip install .

script:
  - haas simplesat
  - cd docs && make html
