language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "pypy"

install:
  - pip install -r dev_requirements.txt
  - pip install .
  - pushd dependencies/enstaller
  - pip install .
  - popd

script:
  - haas simplesat
